/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const WhaleSnapshot = IDL.Record({
  'airdropClaimed' : IDL.Bool,
  'walletAddress' : IDL.Text,
  'nftCount' : IDL.Nat,
  'isVerified' : IDL.Bool,
  'timestamp' : IDL.Int,
  'txHash' : IDL.Opt(IDL.Text),
  'tokenMint' : IDL.Text,
  'tokenBalance' : IDL.Float64,
  'solBalance' : IDL.Float64,
});
export const AllocationBreakdown = IDL.Record({
  'marketing' : IDL.Nat,
  'team' : IDL.Nat,
  'liquidity' : IDL.Nat,
  'community' : IDL.Nat,
  'reserve' : IDL.Nat,
});
export const LaunchData = IDL.Record({
  'decimals' : IDL.Nat8,
  'selectedChain' : IDL.Text,
  'selectedPlatform' : IDL.Text,
  'description' : IDL.Text,
  'supply' : IDL.Nat,
  'allocationBreakdown' : AllocationBreakdown,
  'tokenName' : IDL.Text,
  'paymentTxHash' : IDL.Text,
  'launchType' : IDL.Text,
  'paymentWallet' : IDL.Text,
  'symbol' : IDL.Text,
});
export const TokenMetadata = IDL.Record({
  'decimals' : IDL.Nat8,
  'twitter' : IDL.Opt(IDL.Text),
  'chain' : IDL.Text,
  'mint' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Opt(IDL.Text),
  'website' : IDL.Opt(IDL.Text),
  'imageUrl' : IDL.Opt(IDL.Text),
  'supply' : IDL.Nat,
  'chainId' : IDL.Nat,
  'telegram' : IDL.Opt(IDL.Text),
  'symbol' : IDL.Text,
});
export const BoostRecord = IDL.Record({
  'mint' : IDL.Text,
  'tier' : IDL.Float64,
  'timestamp' : IDL.Int,
  'txHash' : IDL.Text,
  'wallet' : IDL.Text,
});
export const AnalyticsResult = IDL.Record({
  'avgBoostSol' : IDL.Float64,
  'totalBoosts' : IDL.Nat,
  'topWallet' : IDL.Opt(IDL.Text),
  'recentBoosts' : IDL.Vec(BoostRecord),
  'uniqueTokens' : IDL.Nat,
  'totalSolCollected' : IDL.Float64,
});
export const LaunchSnapshot = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'decimals' : IDL.Nat8,
  'selectedChain' : IDL.Text,
  'selectedPlatform' : IDL.Text,
  'description' : IDL.Text,
  'supply' : IDL.Nat,
  'timestamp' : IDL.Int,
  'allocationBreakdown' : AllocationBreakdown,
  'tokenName' : IDL.Text,
  'paymentTxHash' : IDL.Text,
  'launchType' : IDL.Text,
  'paymentWallet' : IDL.Text,
  'symbol' : IDL.Text,
});
export const TelegramStatus = IDL.Record({
  'lastResponse' : IDL.Text,
  'connected' : IDL.Bool,
  'chatId' : IDL.Opt(IDL.Int),
  'errorLog' : IDL.Vec(IDL.Text),
});
export const LeaderboardEntry = IDL.Record({
  'totalSol' : IDL.Float64,
  'tokensBoosted' : IDL.Vec(IDL.Text),
  'lastBoostTimestamp' : IDL.Int,
  'wallet' : IDL.Text,
  'boostCount' : IDL.Nat,
});
export const WalletStats = IDL.Record({
  'totalSol' : IDL.Float64,
  'tokensBoosted' : IDL.Vec(IDL.Text),
  'lastBoostTimestamp' : IDL.Int,
  'wallet' : IDL.Text,
  'recentBoosts' : IDL.Vec(BoostRecord),
  'boostCount' : IDL.Nat,
});
export const WhaleStats = IDL.Record({
  'airdropClaimsCount' : IDL.Nat,
  'totalVerifiedWhales' : IDL.Nat,
  'totalWhalesConnected' : IDL.Nat,
  'totalTokenBalance' : IDL.Float64,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  'autoDiscoverChatId' : IDL.Func([], [IDL.Opt(IDL.Int)], []),
  'claimAirdrop' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'connectWhaleWallet' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Float64, IDL.Float64, IDL.Nat],
      [IDL.Variant({ 'ok' : WhaleSnapshot, 'err' : IDL.Text })],
      [],
    ),
  'createLaunchRecord' : IDL.Func(
      [LaunchData],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'debugTelegramStatus' : IDL.Func([], [IDL.Text], []),
  'fetchTokenMetadata' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : TokenMetadata, 'err' : IDL.Text })],
      [],
    ),
  'forceSetChatId' : IDL.Func([IDL.Int], [], []),
  'getAnalytics' : IDL.Func([], [AnalyticsResult], ['query']),
  'getChatId' : IDL.Func([], [IDL.Opt(IDL.Int)], ['query']),
  'getCurrentChatId' : IDL.Func([], [IDL.Opt(IDL.Int)], ['query']),
  'getDebugInfo' : IDL.Func([], [IDL.Text], []),
  'getLastTelegramError' : IDL.Func([], [IDL.Text], ['query']),
  'getLaunchRecord' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(LaunchSnapshot)],
      ['query'],
    ),
  'getRawUpdates' : IDL.Func([], [IDL.Text], []),
  'getRecentBoosts' : IDL.Func([IDL.Nat], [IDL.Vec(BoostRecord)], ['query']),
  'getTelegramStatus' : IDL.Func([], [TelegramStatus], ['query']),
  'getTelegramUpdates' : IDL.Func(
      [],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'getTokenDetail' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'getTokenHistory' : IDL.Func([IDL.Text], [IDL.Vec(BoostRecord)], ['query']),
  'getTopBoosters' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(LeaderboardEntry)],
      ['query'],
    ),
  'getTopBoostersByPeriod' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Vec(LeaderboardEntry)],
      ['query'],
    ),
  'getTrendingTokens' : IDL.Func(
      [IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'getWalletStats' : IDL.Func([IDL.Text], [IDL.Opt(WalletStats)], ['query']),
  'getWhaleInfo' : IDL.Func([IDL.Text], [IDL.Opt(WhaleSnapshot)], ['query']),
  'getWhaleLeaderboard' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(WhaleSnapshot)],
      ['query'],
    ),
  'getWhaleRecord' : IDL.Func([IDL.Text], [IDL.Opt(WhaleSnapshot)], ['query']),
  'getWhaleStats' : IDL.Func([], [WhaleStats], ['query']),
  'handleTelegramUpdate' : IDL.Func([IDL.Text], [], []),
  'initSeedData' : IDL.Func([], [], []),
  'initializeTelegram' : IDL.Func([IDL.Opt(IDL.Int)], [IDL.Opt(IDL.Int)], []),
  'lookupTokenMultiChain' : IDL.Func(
      [IDL.Text, IDL.Opt(IDL.Text)],
      [IDL.Variant({ 'ok' : TokenMetadata, 'err' : IDL.Text })],
      [],
    ),
  'notifyBoostSubmitted' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'notifyCaPasted' : IDL.Func([IDL.Text], [], []),
  'notifyPackageSelected' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'notifySiteVisit' : IDL.Func([IDL.Text], [], []),
  'notifyTxHashEntered' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'recordAction' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'recordBoost' : IDL.Func(
      [IDL.Text, IDL.Float64, IDL.Text, IDL.Int],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'recordBoostWithWallet' : IDL.Func(
      [IDL.Text, IDL.Float64, IDL.Text, IDL.Int, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'recordWhaleConnect' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Float64, IDL.Int],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'registerWhaleAirdrop' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : WhaleSnapshot, 'err' : IDL.Text })],
      [],
    ),
  'sendTelegramMessage' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'sendTestMessage' : IDL.Func([], [IDL.Text], []),
  'setChatId' : IDL.Func([IDL.Int], [], []),
  'setChatIdFromGroup' : IDL.Func([], [IDL.Text], []),
  'submitWhaleVerification' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'transformDexscreener' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'transformHelius' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'transformJupiter' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'transformSolscan' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const WhaleSnapshot = IDL.Record({
    'airdropClaimed' : IDL.Bool,
    'walletAddress' : IDL.Text,
    'nftCount' : IDL.Nat,
    'isVerified' : IDL.Bool,
    'timestamp' : IDL.Int,
    'txHash' : IDL.Opt(IDL.Text),
    'tokenMint' : IDL.Text,
    'tokenBalance' : IDL.Float64,
    'solBalance' : IDL.Float64,
  });
  const AllocationBreakdown = IDL.Record({
    'marketing' : IDL.Nat,
    'team' : IDL.Nat,
    'liquidity' : IDL.Nat,
    'community' : IDL.Nat,
    'reserve' : IDL.Nat,
  });
  const LaunchData = IDL.Record({
    'decimals' : IDL.Nat8,
    'selectedChain' : IDL.Text,
    'selectedPlatform' : IDL.Text,
    'description' : IDL.Text,
    'supply' : IDL.Nat,
    'allocationBreakdown' : AllocationBreakdown,
    'tokenName' : IDL.Text,
    'paymentTxHash' : IDL.Text,
    'launchType' : IDL.Text,
    'paymentWallet' : IDL.Text,
    'symbol' : IDL.Text,
  });
  const TokenMetadata = IDL.Record({
    'decimals' : IDL.Nat8,
    'twitter' : IDL.Opt(IDL.Text),
    'chain' : IDL.Text,
    'mint' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Opt(IDL.Text),
    'website' : IDL.Opt(IDL.Text),
    'imageUrl' : IDL.Opt(IDL.Text),
    'supply' : IDL.Nat,
    'chainId' : IDL.Nat,
    'telegram' : IDL.Opt(IDL.Text),
    'symbol' : IDL.Text,
  });
  const BoostRecord = IDL.Record({
    'mint' : IDL.Text,
    'tier' : IDL.Float64,
    'timestamp' : IDL.Int,
    'txHash' : IDL.Text,
    'wallet' : IDL.Text,
  });
  const AnalyticsResult = IDL.Record({
    'avgBoostSol' : IDL.Float64,
    'totalBoosts' : IDL.Nat,
    'topWallet' : IDL.Opt(IDL.Text),
    'recentBoosts' : IDL.Vec(BoostRecord),
    'uniqueTokens' : IDL.Nat,
    'totalSolCollected' : IDL.Float64,
  });
  const LaunchSnapshot = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'decimals' : IDL.Nat8,
    'selectedChain' : IDL.Text,
    'selectedPlatform' : IDL.Text,
    'description' : IDL.Text,
    'supply' : IDL.Nat,
    'timestamp' : IDL.Int,
    'allocationBreakdown' : AllocationBreakdown,
    'tokenName' : IDL.Text,
    'paymentTxHash' : IDL.Text,
    'launchType' : IDL.Text,
    'paymentWallet' : IDL.Text,
    'symbol' : IDL.Text,
  });
  const TelegramStatus = IDL.Record({
    'lastResponse' : IDL.Text,
    'connected' : IDL.Bool,
    'chatId' : IDL.Opt(IDL.Int),
    'errorLog' : IDL.Vec(IDL.Text),
  });
  const LeaderboardEntry = IDL.Record({
    'totalSol' : IDL.Float64,
    'tokensBoosted' : IDL.Vec(IDL.Text),
    'lastBoostTimestamp' : IDL.Int,
    'wallet' : IDL.Text,
    'boostCount' : IDL.Nat,
  });
  const WalletStats = IDL.Record({
    'totalSol' : IDL.Float64,
    'tokensBoosted' : IDL.Vec(IDL.Text),
    'lastBoostTimestamp' : IDL.Int,
    'wallet' : IDL.Text,
    'recentBoosts' : IDL.Vec(BoostRecord),
    'boostCount' : IDL.Nat,
  });
  const WhaleStats = IDL.Record({
    'airdropClaimsCount' : IDL.Nat,
    'totalVerifiedWhales' : IDL.Nat,
    'totalWhalesConnected' : IDL.Nat,
    'totalTokenBalance' : IDL.Float64,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    'autoDiscoverChatId' : IDL.Func([], [IDL.Opt(IDL.Int)], []),
    'claimAirdrop' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'connectWhaleWallet' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Float64, IDL.Float64, IDL.Nat],
        [IDL.Variant({ 'ok' : WhaleSnapshot, 'err' : IDL.Text })],
        [],
      ),
    'createLaunchRecord' : IDL.Func(
        [LaunchData],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'debugTelegramStatus' : IDL.Func([], [IDL.Text], []),
    'fetchTokenMetadata' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : TokenMetadata, 'err' : IDL.Text })],
        [],
      ),
    'forceSetChatId' : IDL.Func([IDL.Int], [], []),
    'getAnalytics' : IDL.Func([], [AnalyticsResult], ['query']),
    'getChatId' : IDL.Func([], [IDL.Opt(IDL.Int)], ['query']),
    'getCurrentChatId' : IDL.Func([], [IDL.Opt(IDL.Int)], ['query']),
    'getDebugInfo' : IDL.Func([], [IDL.Text], []),
    'getLastTelegramError' : IDL.Func([], [IDL.Text], ['query']),
    'getLaunchRecord' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(LaunchSnapshot)],
        ['query'],
      ),
    'getRawUpdates' : IDL.Func([], [IDL.Text], []),
    'getRecentBoosts' : IDL.Func([IDL.Nat], [IDL.Vec(BoostRecord)], ['query']),
    'getTelegramStatus' : IDL.Func([], [TelegramStatus], ['query']),
    'getTelegramUpdates' : IDL.Func(
        [],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'getTokenDetail' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'getTokenHistory' : IDL.Func([IDL.Text], [IDL.Vec(BoostRecord)], ['query']),
    'getTopBoosters' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(LeaderboardEntry)],
        ['query'],
      ),
    'getTopBoostersByPeriod' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(LeaderboardEntry)],
        ['query'],
      ),
    'getTrendingTokens' : IDL.Func(
        [IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'getWalletStats' : IDL.Func([IDL.Text], [IDL.Opt(WalletStats)], ['query']),
    'getWhaleInfo' : IDL.Func([IDL.Text], [IDL.Opt(WhaleSnapshot)], ['query']),
    'getWhaleLeaderboard' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(WhaleSnapshot)],
        ['query'],
      ),
    'getWhaleRecord' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(WhaleSnapshot)],
        ['query'],
      ),
    'getWhaleStats' : IDL.Func([], [WhaleStats], ['query']),
    'handleTelegramUpdate' : IDL.Func([IDL.Text], [], []),
    'initSeedData' : IDL.Func([], [], []),
    'initializeTelegram' : IDL.Func([IDL.Opt(IDL.Int)], [IDL.Opt(IDL.Int)], []),
    'lookupTokenMultiChain' : IDL.Func(
        [IDL.Text, IDL.Opt(IDL.Text)],
        [IDL.Variant({ 'ok' : TokenMetadata, 'err' : IDL.Text })],
        [],
      ),
    'notifyBoostSubmitted' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'notifyCaPasted' : IDL.Func([IDL.Text], [], []),
    'notifyPackageSelected' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'notifySiteVisit' : IDL.Func([IDL.Text], [], []),
    'notifyTxHashEntered' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'recordAction' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'recordBoost' : IDL.Func(
        [IDL.Text, IDL.Float64, IDL.Text, IDL.Int],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'recordBoostWithWallet' : IDL.Func(
        [IDL.Text, IDL.Float64, IDL.Text, IDL.Int, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'recordWhaleConnect' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Float64, IDL.Int],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'registerWhaleAirdrop' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : WhaleSnapshot, 'err' : IDL.Text })],
        [],
      ),
    'sendTelegramMessage' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'sendTestMessage' : IDL.Func([], [IDL.Text], []),
    'setChatId' : IDL.Func([IDL.Int], [], []),
    'setChatIdFromGroup' : IDL.Func([], [IDL.Text], []),
    'submitWhaleVerification' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'transformDexscreener' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'transformHelius' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'transformJupiter' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'transformSolscan' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };