/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AllocationBreakdown {
  'marketing' : bigint,
  'team' : bigint,
  'liquidity' : bigint,
  'community' : bigint,
  'reserve' : bigint,
}
export interface AnalyticsResult {
  'avgBoostSol' : number,
  'totalBoosts' : bigint,
  'topWallet' : [] | [string],
  'recentBoosts' : Array<BoostRecord>,
  'uniqueTokens' : bigint,
  'totalSolCollected' : number,
}
export interface BoostRecord {
  'mint' : string,
  'tier' : number,
  'timestamp' : bigint,
  'txHash' : string,
  'wallet' : string,
}
export interface LaunchData {
  'decimals' : number,
  'selectedChain' : string,
  'selectedPlatform' : string,
  'description' : string,
  'supply' : bigint,
  'allocationBreakdown' : AllocationBreakdown,
  'tokenName' : string,
  'paymentTxHash' : string,
  'launchType' : string,
  'paymentWallet' : string,
  'symbol' : string,
}
export interface LaunchSnapshot {
  'id' : string,
  'status' : string,
  'decimals' : number,
  'selectedChain' : string,
  'selectedPlatform' : string,
  'description' : string,
  'supply' : bigint,
  'timestamp' : bigint,
  'allocationBreakdown' : AllocationBreakdown,
  'tokenName' : string,
  'paymentTxHash' : string,
  'launchType' : string,
  'paymentWallet' : string,
  'symbol' : string,
}
export interface LeaderboardEntry {
  'totalSol' : number,
  'tokensBoosted' : Array<string>,
  'lastBoostTimestamp' : bigint,
  'wallet' : string,
  'boostCount' : bigint,
}
export interface TelegramStatus {
  'lastResponse' : string,
  'connected' : boolean,
  'chatId' : [] | [bigint],
  'errorLog' : Array<string>,
}
export interface TokenMetadata {
  'decimals' : number,
  'twitter' : [] | [string],
  'chain' : string,
  'mint' : string,
  'name' : string,
  'description' : [] | [string],
  'website' : [] | [string],
  'imageUrl' : [] | [string],
  'supply' : bigint,
  'chainId' : bigint,
  'telegram' : [] | [string],
  'symbol' : string,
}
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface WalletStats {
  'totalSol' : number,
  'tokensBoosted' : Array<string>,
  'lastBoostTimestamp' : bigint,
  'wallet' : string,
  'recentBoosts' : Array<BoostRecord>,
  'boostCount' : bigint,
}
export interface WhaleSnapshot {
  'airdropClaimed' : boolean,
  'walletAddress' : string,
  'nftCount' : bigint,
  'isVerified' : boolean,
  'timestamp' : bigint,
  'txHash' : [] | [string],
  'tokenMint' : string,
  'tokenBalance' : number,
  'solBalance' : number,
}
export interface WhaleStats {
  'airdropClaimsCount' : bigint,
  'totalVerifiedWhales' : bigint,
  'totalWhalesConnected' : bigint,
  'totalTokenBalance' : number,
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  'autoDiscoverChatId' : ActorMethod<[], [] | [bigint]>,
  'claimAirdrop' : ActorMethod<[string], { 'ok' : null } | { 'err' : string }>,
  'connectWhaleWallet' : ActorMethod<
    [string, string, number, number, bigint],
    { 'ok' : WhaleSnapshot } |
      { 'err' : string }
  >,
  'createLaunchRecord' : ActorMethod<
    [LaunchData],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'debugTelegramStatus' : ActorMethod<[], string>,
  /**
   * / Fetch real on-chain token metadata using a three-source Solana cascade:
   * /   1. Solscan (primary)  2. Jupiter (fallback)  3. Dexscreener (fallback)
   */
  'fetchTokenMetadata' : ActorMethod<
    [string],
    { 'ok' : TokenMetadata } |
      { 'err' : string }
  >,
  'forceSetChatId' : ActorMethod<[bigint], undefined>,
  'getAnalytics' : ActorMethod<[], AnalyticsResult>,
  'getChatId' : ActorMethod<[], [] | [bigint]>,
  'getCurrentChatId' : ActorMethod<[], [] | [bigint]>,
  'getDebugInfo' : ActorMethod<[], string>,
  'getLastTelegramError' : ActorMethod<[], string>,
  'getLaunchRecord' : ActorMethod<[string], [] | [LaunchSnapshot]>,
  'getRawUpdates' : ActorMethod<[], string>,
  'getRecentBoosts' : ActorMethod<[bigint], Array<BoostRecord>>,
  'getTelegramStatus' : ActorMethod<[], TelegramStatus>,
  'getTelegramUpdates' : ActorMethod<
    [],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'getTokenDetail' : ActorMethod<
    [string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'getTokenHistory' : ActorMethod<[string], Array<BoostRecord>>,
  'getTopBoosters' : ActorMethod<[bigint], Array<LeaderboardEntry>>,
  'getTopBoostersByPeriod' : ActorMethod<
    [bigint, bigint],
    Array<LeaderboardEntry>
  >,
  'getTrendingTokens' : ActorMethod<
    [bigint],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'getWalletStats' : ActorMethod<[string], [] | [WalletStats]>,
  'getWhaleInfo' : ActorMethod<[string], [] | [WhaleSnapshot]>,
  'getWhaleLeaderboard' : ActorMethod<[bigint], Array<WhaleSnapshot>>,
  'getWhaleRecord' : ActorMethod<[string], [] | [WhaleSnapshot]>,
  'getWhaleStats' : ActorMethod<[], WhaleStats>,
  'handleTelegramUpdate' : ActorMethod<[string], undefined>,
  'initSeedData' : ActorMethod<[], undefined>,
  'initializeTelegram' : ActorMethod<[[] | [bigint]], [] | [bigint]>,
  /**
   * / Multi-chain token lookup: auto-detects Solana vs EVM from CA format.
   * / chainHint (optional): "ethereum", "base", "bsc", "polygon", "arbitrum", "avalanche"
   */
  'lookupTokenMultiChain' : ActorMethod<
    [string, [] | [string]],
    { 'ok' : TokenMetadata } |
      { 'err' : string }
  >,
  'notifyBoostSubmitted' : ActorMethod<
    [string, string, string, string],
    undefined
  >,
  'notifyCaPasted' : ActorMethod<[string], undefined>,
  'notifyPackageSelected' : ActorMethod<[string, string], undefined>,
  'notifySiteVisit' : ActorMethod<[string], undefined>,
  'notifyTxHashEntered' : ActorMethod<[string, string], undefined>,
  'recordAction' : ActorMethod<[string, string], undefined>,
  'recordBoost' : ActorMethod<
    [string, number, string, bigint],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'recordBoostWithWallet' : ActorMethod<
    [string, number, string, bigint, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'recordWhaleConnect' : ActorMethod<
    [string, string, number, bigint],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'registerWhaleAirdrop' : ActorMethod<
    [string, string],
    { 'ok' : WhaleSnapshot } |
      { 'err' : string }
  >,
  'sendTelegramMessage' : ActorMethod<[string], boolean>,
  'sendTestMessage' : ActorMethod<[], string>,
  'setChatId' : ActorMethod<[bigint], undefined>,
  'setChatIdFromGroup' : ActorMethod<[], string>,
  'submitWhaleVerification' : ActorMethod<
    [string, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'transformDexscreener' : ActorMethod<
    [TransformationInput],
    TransformationOutput
  >,
  'transformHelius' : ActorMethod<[TransformationInput], TransformationOutput>,
  'transformJupiter' : ActorMethod<[TransformationInput], TransformationOutput>,
  'transformSolscan' : ActorMethod<[TransformationInput], TransformationOutput>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];