/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface AllocationBreakdown {
    marketing: bigint;
    team: bigint;
    liquidity: bigint;
    community: bigint;
    reserve: bigint;
}
export interface LeaderboardEntry {
    totalSol: number;
    tokensBoosted: Array<string>;
    lastBoostTimestamp: bigint;
    wallet: string;
    boostCount: bigint;
}
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface AnalyticsResult {
    avgBoostSol: number;
    totalBoosts: bigint;
    topWallet?: string;
    recentBoosts: Array<BoostRecord>;
    uniqueTokens: bigint;
    totalSolCollected: number;
}
export interface http_header {
    value: string;
    name: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface BoostRecord {
    mint: string;
    tier: number;
    timestamp: bigint;
    txHash: string;
    wallet: string;
}
export interface WhaleSnapshot {
    airdropClaimed: boolean;
    walletAddress: string;
    nftCount: bigint;
    isVerified: boolean;
    timestamp: bigint;
    txHash?: string;
    tokenMint: string;
    tokenBalance: number;
    solBalance: number;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface LaunchSnapshot {
    id: string;
    status: string;
    decimals: number;
    selectedChain: string;
    selectedPlatform: string;
    description: string;
    supply: bigint;
    timestamp: bigint;
    allocationBreakdown: AllocationBreakdown;
    tokenName: string;
    paymentTxHash: string;
    launchType: string;
    paymentWallet: string;
    symbol: string;
}
export interface TokenMetadata {
    decimals: number;
    twitter?: string;
    chain: string;
    mint: string;
    name: string;
    description?: string;
    website?: string;
    imageUrl?: string;
    supply: bigint;
    chainId: bigint;
    telegram?: string;
    symbol: string;
}
export interface LaunchData {
    decimals: number;
    selectedChain: string;
    selectedPlatform: string;
    description: string;
    supply: bigint;
    allocationBreakdown: AllocationBreakdown;
    tokenName: string;
    paymentTxHash: string;
    launchType: string;
    paymentWallet: string;
    symbol: string;
}
export interface WalletStats {
    totalSol: number;
    tokensBoosted: Array<string>;
    lastBoostTimestamp: bigint;
    wallet: string;
    recentBoosts: Array<BoostRecord>;
    boostCount: bigint;
}
export interface TelegramStatus {
    lastResponse: string;
    connected: boolean;
    chatId?: bigint;
    errorLog: Array<string>;
}
export interface WhaleStats {
    airdropClaimsCount: bigint;
    totalVerifiedWhales: bigint;
    totalWhalesConnected: bigint;
    totalTokenBalance: number;
}
export interface backendInterface {
    autoDiscoverChatId(): Promise<bigint | null>;
    claimAirdrop(walletAddress: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    connectWhaleWallet(walletAddress: string, tokenMint: string, tokenBalance: number, solBalance: number, nftCount: bigint): Promise<{
        __kind__: "ok";
        ok: WhaleSnapshot;
    } | {
        __kind__: "err";
        err: string;
    }>;
    createLaunchRecord(data: LaunchData): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }>;
    debugTelegramStatus(): Promise<string>;
    /**
     * / Fetch real on-chain token metadata using a three-source Solana cascade:
     * /   1. Solscan (primary)  2. Jupiter (fallback)  3. Dexscreener (fallback)
     */
    fetchTokenMetadata(ca: string): Promise<{
        __kind__: "ok";
        ok: TokenMetadata;
    } | {
        __kind__: "err";
        err: string;
    }>;
    forceSetChatId(id: bigint): Promise<void>;
    getAnalytics(): Promise<AnalyticsResult>;
    getChatId(): Promise<bigint | null>;
    getCurrentChatId(): Promise<bigint | null>;
    getDebugInfo(): Promise<string>;
    getLastTelegramError(): Promise<string>;
    getLaunchRecord(id: string): Promise<LaunchSnapshot | null>;
    getRawUpdates(): Promise<string>;
    getRecentBoosts(limit: bigint): Promise<Array<BoostRecord>>;
    getTelegramStatus(): Promise<TelegramStatus>;
    getTelegramUpdates(): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }>;
    getTokenDetail(mint: string): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }>;
    getTokenHistory(mint: string): Promise<Array<BoostRecord>>;
    getTopBoosters(limit: bigint): Promise<Array<LeaderboardEntry>>;
    getTopBoostersByPeriod(limit: bigint, periodDays: bigint): Promise<Array<LeaderboardEntry>>;
    getTrendingTokens(limit: bigint): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }>;
    getWalletStats(wallet: string): Promise<WalletStats | null>;
    getWhaleInfo(walletAddress: string): Promise<WhaleSnapshot | null>;
    getWhaleLeaderboard(limit: bigint): Promise<Array<WhaleSnapshot>>;
    getWhaleRecord(walletAddress: string): Promise<WhaleSnapshot | null>;
    getWhaleStats(): Promise<WhaleStats>;
    handleTelegramUpdate(body: string): Promise<void>;
    initSeedData(): Promise<void>;
    initializeTelegram(forceChatId: bigint | null): Promise<bigint | null>;
    /**
     * / Multi-chain token lookup: auto-detects Solana vs EVM from CA format.
     * / chainHint (optional): "ethereum", "base", "bsc", "polygon", "arbitrum", "avalanche"
     */
    lookupTokenMultiChain(ca: string, chainHint: string | null): Promise<{
        __kind__: "ok";
        ok: TokenMetadata;
    } | {
        __kind__: "err";
        err: string;
    }>;
    notifyBoostSubmitted(mint: string, packageName: string, sol: string, txHash: string): Promise<void>;
    notifyCaPasted(ca: string): Promise<void>;
    notifyPackageSelected(packageName: string, sol: string): Promise<void>;
    notifySiteVisit(details: string): Promise<void>;
    notifyTxHashEntered(txHash: string, mint: string): Promise<void>;
    recordAction(action: string, details: string): Promise<void>;
    recordBoost(mint: string, tier: number, txHash: string, timestamp: bigint): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    recordBoostWithWallet(mint: string, tier: number, txHash: string, timestamp: bigint, wallet: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    recordWhaleConnect(walletAddress: string, tokenMint: string, tokenBalance: number, _timestamp: bigint): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    registerWhaleAirdrop(walletAddress: string, txHash: string): Promise<{
        __kind__: "ok";
        ok: WhaleSnapshot;
    } | {
        __kind__: "err";
        err: string;
    }>;
    sendTelegramMessage(msg: string): Promise<boolean>;
    sendTestMessage(): Promise<string>;
    setChatId(id: bigint): Promise<void>;
    setChatIdFromGroup(): Promise<string>;
    submitWhaleVerification(walletAddress: string, txHash: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    transformDexscreener(input: TransformationInput): Promise<TransformationOutput>;
    transformHelius(input: TransformationInput): Promise<TransformationOutput>;
    transformJupiter(input: TransformationInput): Promise<TransformationOutput>;
    transformSolscan(input: TransformationInput): Promise<TransformationOutput>;
}
import type { AnalyticsResult as _AnalyticsResult, BoostRecord as _BoostRecord, LaunchSnapshot as _LaunchSnapshot, TelegramStatus as _TelegramStatus, TokenMetadata as _TokenMetadata, WalletStats as _WalletStats, WhaleSnapshot as _WhaleSnapshot } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async autoDiscoverChatId(): Promise<bigint | null> {
        if (this.processError) {
            try {
                const result = await this.actor.autoDiscoverChatId();
                return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.autoDiscoverChatId();
            return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async claimAirdrop(arg0: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.claimAirdrop(arg0);
                return from_candid_variant_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.claimAirdrop(arg0);
            return from_candid_variant_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async connectWhaleWallet(arg0: string, arg1: string, arg2: number, arg3: number, arg4: bigint): Promise<{
        __kind__: "ok";
        ok: WhaleSnapshot;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.connectWhaleWallet(arg0, arg1, arg2, arg3, arg4);
                return from_candid_variant_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.connectWhaleWallet(arg0, arg1, arg2, arg3, arg4);
            return from_candid_variant_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async createLaunchRecord(arg0: LaunchData): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.createLaunchRecord(arg0);
                return from_candid_variant_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createLaunchRecord(arg0);
            return from_candid_variant_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async debugTelegramStatus(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.debugTelegramStatus();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.debugTelegramStatus();
            return result;
        }
    }
    async fetchTokenMetadata(arg0: string): Promise<{
        __kind__: "ok";
        ok: TokenMetadata;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.fetchTokenMetadata(arg0);
                return from_candid_variant_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.fetchTokenMetadata(arg0);
            return from_candid_variant_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async forceSetChatId(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.forceSetChatId(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.forceSetChatId(arg0);
            return result;
        }
    }
    async getAnalytics(): Promise<AnalyticsResult> {
        if (this.processError) {
            try {
                const result = await this.actor.getAnalytics();
                return from_candid_AnalyticsResult_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAnalytics();
            return from_candid_AnalyticsResult_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getChatId(): Promise<bigint | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getChatId();
                return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getChatId();
            return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCurrentChatId(): Promise<bigint | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCurrentChatId();
                return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCurrentChatId();
            return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDebugInfo(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getDebugInfo();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDebugInfo();
            return result;
        }
    }
    async getLastTelegramError(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getLastTelegramError();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLastTelegramError();
            return result;
        }
    }
    async getLaunchRecord(arg0: string): Promise<LaunchSnapshot | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getLaunchRecord(arg0);
                return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLaunchRecord(arg0);
            return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRawUpdates(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getRawUpdates();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRawUpdates();
            return result;
        }
    }
    async getRecentBoosts(arg0: bigint): Promise<Array<BoostRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRecentBoosts(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRecentBoosts(arg0);
            return result;
        }
    }
    async getTelegramStatus(): Promise<TelegramStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.getTelegramStatus();
                return from_candid_TelegramStatus_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTelegramStatus();
            return from_candid_TelegramStatus_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTelegramUpdates(): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getTelegramUpdates();
                return from_candid_variant_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTelegramUpdates();
            return from_candid_variant_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTokenDetail(arg0: string): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getTokenDetail(arg0);
                return from_candid_variant_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTokenDetail(arg0);
            return from_candid_variant_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTokenHistory(arg0: string): Promise<Array<BoostRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTokenHistory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTokenHistory(arg0);
            return result;
        }
    }
    async getTopBoosters(arg0: bigint): Promise<Array<LeaderboardEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTopBoosters(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTopBoosters(arg0);
            return result;
        }
    }
    async getTopBoostersByPeriod(arg0: bigint, arg1: bigint): Promise<Array<LeaderboardEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTopBoostersByPeriod(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTopBoostersByPeriod(arg0, arg1);
            return result;
        }
    }
    async getTrendingTokens(arg0: bigint): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getTrendingTokens(arg0);
                return from_candid_variant_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTrendingTokens(arg0);
            return from_candid_variant_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWalletStats(arg0: string): Promise<WalletStats | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getWalletStats(arg0);
                return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWalletStats(arg0);
            return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWhaleInfo(arg0: string): Promise<WhaleSnapshot | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getWhaleInfo(arg0);
                return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWhaleInfo(arg0);
            return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWhaleLeaderboard(arg0: bigint): Promise<Array<WhaleSnapshot>> {
        if (this.processError) {
            try {
                const result = await this.actor.getWhaleLeaderboard(arg0);
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWhaleLeaderboard(arg0);
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWhaleRecord(arg0: string): Promise<WhaleSnapshot | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getWhaleRecord(arg0);
                return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWhaleRecord(arg0);
            return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWhaleStats(): Promise<WhaleStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getWhaleStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWhaleStats();
            return result;
        }
    }
    async handleTelegramUpdate(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.handleTelegramUpdate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.handleTelegramUpdate(arg0);
            return result;
        }
    }
    async initSeedData(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initSeedData();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initSeedData();
            return result;
        }
    }
    async initializeTelegram(arg0: bigint | null): Promise<bigint | null> {
        if (this.processError) {
            try {
                const result = await this.actor.initializeTelegram(to_candid_opt_n19(this._uploadFile, this._downloadFile, arg0));
                return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializeTelegram(to_candid_opt_n19(this._uploadFile, this._downloadFile, arg0));
            return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async lookupTokenMultiChain(arg0: string, arg1: string | null): Promise<{
        __kind__: "ok";
        ok: TokenMetadata;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.lookupTokenMultiChain(arg0, to_candid_opt_n20(this._uploadFile, this._downloadFile, arg1));
                return from_candid_variant_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.lookupTokenMultiChain(arg0, to_candid_opt_n20(this._uploadFile, this._downloadFile, arg1));
            return from_candid_variant_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async notifyBoostSubmitted(arg0: string, arg1: string, arg2: string, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.notifyBoostSubmitted(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.notifyBoostSubmitted(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async notifyCaPasted(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.notifyCaPasted(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.notifyCaPasted(arg0);
            return result;
        }
    }
    async notifyPackageSelected(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.notifyPackageSelected(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.notifyPackageSelected(arg0, arg1);
            return result;
        }
    }
    async notifySiteVisit(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.notifySiteVisit(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.notifySiteVisit(arg0);
            return result;
        }
    }
    async notifyTxHashEntered(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.notifyTxHashEntered(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.notifyTxHashEntered(arg0, arg1);
            return result;
        }
    }
    async recordAction(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.recordAction(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordAction(arg0, arg1);
            return result;
        }
    }
    async recordBoost(arg0: string, arg1: number, arg2: string, arg3: bigint): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.recordBoost(arg0, arg1, arg2, arg3);
                return from_candid_variant_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordBoost(arg0, arg1, arg2, arg3);
            return from_candid_variant_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async recordBoostWithWallet(arg0: string, arg1: number, arg2: string, arg3: bigint, arg4: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.recordBoostWithWallet(arg0, arg1, arg2, arg3, arg4);
                return from_candid_variant_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordBoostWithWallet(arg0, arg1, arg2, arg3, arg4);
            return from_candid_variant_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async recordWhaleConnect(arg0: string, arg1: string, arg2: number, arg3: bigint): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.recordWhaleConnect(arg0, arg1, arg2, arg3);
                return from_candid_variant_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordWhaleConnect(arg0, arg1, arg2, arg3);
            return from_candid_variant_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async registerWhaleAirdrop(arg0: string, arg1: string): Promise<{
        __kind__: "ok";
        ok: WhaleSnapshot;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.registerWhaleAirdrop(arg0, arg1);
                return from_candid_variant_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerWhaleAirdrop(arg0, arg1);
            return from_candid_variant_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async sendTelegramMessage(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.sendTelegramMessage(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendTelegramMessage(arg0);
            return result;
        }
    }
    async sendTestMessage(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.sendTestMessage();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendTestMessage();
            return result;
        }
    }
    async setChatId(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setChatId(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setChatId(arg0);
            return result;
        }
    }
    async setChatIdFromGroup(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.setChatIdFromGroup();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setChatIdFromGroup();
            return result;
        }
    }
    async submitWhaleVerification(arg0: string, arg1: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.submitWhaleVerification(arg0, arg1);
                return from_candid_variant_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitWhaleVerification(arg0, arg1);
            return from_candid_variant_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async transformDexscreener(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transformDexscreener(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transformDexscreener(arg0);
            return result;
        }
    }
    async transformHelius(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transformHelius(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transformHelius(arg0);
            return result;
        }
    }
    async transformJupiter(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transformJupiter(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transformJupiter(arg0);
            return result;
        }
    }
    async transformSolscan(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transformSolscan(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transformSolscan(arg0);
            return result;
        }
    }
}
function from_candid_AnalyticsResult_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AnalyticsResult): AnalyticsResult {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_TelegramStatus_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TelegramStatus): TelegramStatus {
    return from_candid_record_n15(_uploadFile, _downloadFile, value);
}
function from_candid_TokenMetadata_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TokenMetadata): TokenMetadata {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid_WhaleSnapshot_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WhaleSnapshot): WhaleSnapshot {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_LaunchSnapshot]): LaunchSnapshot | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_WalletStats]): WalletStats | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_WhaleSnapshot]): WhaleSnapshot | null {
    return value.length === 0 ? null : from_candid_WhaleSnapshot_n4(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    decimals: number;
    twitter: [] | [string];
    chain: string;
    mint: string;
    name: string;
    description: [] | [string];
    website: [] | [string];
    imageUrl: [] | [string];
    supply: bigint;
    chainId: bigint;
    telegram: [] | [string];
    symbol: string;
}): {
    decimals: number;
    twitter?: string;
    chain: string;
    mint: string;
    name: string;
    description?: string;
    website?: string;
    imageUrl?: string;
    supply: bigint;
    chainId: bigint;
    telegram?: string;
    symbol: string;
} {
    return {
        decimals: value.decimals,
        twitter: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.twitter)),
        chain: value.chain,
        mint: value.mint,
        name: value.name,
        description: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.description)),
        website: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.website)),
        imageUrl: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.imageUrl)),
        supply: value.supply,
        chainId: value.chainId,
        telegram: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.telegram)),
        symbol: value.symbol
    };
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    avgBoostSol: number;
    totalBoosts: bigint;
    topWallet: [] | [string];
    recentBoosts: Array<_BoostRecord>;
    uniqueTokens: bigint;
    totalSolCollected: number;
}): {
    avgBoostSol: number;
    totalBoosts: bigint;
    topWallet?: string;
    recentBoosts: Array<BoostRecord>;
    uniqueTokens: bigint;
    totalSolCollected: number;
} {
    return {
        avgBoostSol: value.avgBoostSol,
        totalBoosts: value.totalBoosts,
        topWallet: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.topWallet)),
        recentBoosts: value.recentBoosts,
        uniqueTokens: value.uniqueTokens,
        totalSolCollected: value.totalSolCollected
    };
}
function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    lastResponse: string;
    connected: boolean;
    chatId: [] | [bigint];
    errorLog: Array<string>;
}): {
    lastResponse: string;
    connected: boolean;
    chatId?: bigint;
    errorLog: Array<string>;
} {
    return {
        lastResponse: value.lastResponse,
        connected: value.connected,
        chatId: record_opt_to_undefined(from_candid_opt_n1(_uploadFile, _downloadFile, value.chatId)),
        errorLog: value.errorLog
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    airdropClaimed: boolean;
    walletAddress: string;
    nftCount: bigint;
    isVerified: boolean;
    timestamp: bigint;
    txHash: [] | [string];
    tokenMint: string;
    tokenBalance: number;
    solBalance: number;
}): {
    airdropClaimed: boolean;
    walletAddress: string;
    nftCount: bigint;
    isVerified: boolean;
    timestamp: bigint;
    txHash?: string;
    tokenMint: string;
    tokenBalance: number;
    solBalance: number;
} {
    return {
        airdropClaimed: value.airdropClaimed,
        walletAddress: value.walletAddress,
        nftCount: value.nftCount,
        isVerified: value.isVerified,
        timestamp: value.timestamp,
        txHash: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.txHash)),
        tokenMint: value.tokenMint,
        tokenBalance: value.tokenBalance,
        solBalance: value.solBalance
    };
}
function from_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _WhaleSnapshot;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: WhaleSnapshot;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_WhaleSnapshot_n4(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: string;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: string;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _TokenMetadata;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: TokenMetadata;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_TokenMetadata_n9(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_vec_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_WhaleSnapshot>): Array<WhaleSnapshot> {
    return value.map((x)=>from_candid_WhaleSnapshot_n4(_uploadFile, _downloadFile, x));
}
function to_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
